#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TravailFinEtudes.Resource", IsApplication=true)]

namespace TravailFinEtudes
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040002
			public const int ButtonFilter = 2130968578;
			
			// aapt resource value: 0x7f040010
			public const int SelectedImage = 2130968592;
			
			// aapt resource value: 0x7f04000d
			public const int absoluteLayout1 = 2130968589;
			
			// aapt resource value: 0x7f040003
			public const int averagePicker = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int buttonDelete = 2130968582;
			
			// aapt resource value: 0x7f04000f
			public const int buttonList = 2130968591;
			
			// aapt resource value: 0x7f040007
			public const int buttonPilot = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int buttonSave = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int buttonScan = 2130968580;
			
			// aapt resource value: 0x7f04000e
			public const int buttonStart = 2130968590;
			
			// aapt resource value: 0x7f04000c
			public const int checkBoxParam = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int editTextIp = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int editTextPort = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int linearLayout1 = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int screenDrawer = 2130968584;
			
			// aapt resource value: 0x7f040001
			public const int selectedMode = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int textView1 = 2130968585;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Command = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Main = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ObstacleList = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ObstacleView = 2130837507;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030009
			public const int AdressError = 2130903049;
			
			// aapt resource value: 0x7f030007
			public const int AlreadyConnected = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int CanvasError = 2130903048;
			
			// aapt resource value: 0x7f030006
			public const int Connect = 2130903046;
			
			// aapt resource value: 0x7f030004
			public const int ConnectFailed = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Deconnected = 2130903045;
			
			// aapt resource value: 0x7f030003
			public const int DeconnectionError = 2130903043;
			
			// aapt resource value: 0x7f030002
			public const int DefaultConnexionPort = 2130903042;
			
			// aapt resource value: 0x7f030001
			public const int DefaultIpAdress = 2130903041;
			
			// aapt resource value: 0x7f03000e
			public const int ErrorDeletingImage = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int ErrorImageDirectory = 2130903055;
			
			// aapt resource value: 0x7f03000b
			public const int ImageDirectory = 2130903051;
			
			// aapt resource value: 0x7f03000a
			public const int ImageSaved = 2130903050;
			
			// aapt resource value: 0x7f03000d
			public const int ImageSupprimée = 2130903053;
			
			// aapt resource value: 0x7f03000c
			public const int JSONObjectsDirectory = 2130903052;
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
